#!/usr/bin/env python3
"""
动态行为检测器 - 检测时序攻击、混淆代码、AI生成恶意代码
功能:
1. 时序攻击检测 (延迟注入、条件触发)
2. 混淆代码识别 (Base64 多层嵌套、字符串变形)
3. AI 生成恶意代码识别
4. 行为沙箱模拟

用法:
    python3 dynamic_detector.py --file suspicious.py
"""

import os
import sys
import re
import json
import hashlib
import base64
import ast
from datetime import datetime
from collections import Counter

def log(msg):
    print(f"[{datetime.now().strftime('%H:%M:%S')}] {msg}")

class DynamicBehaviorDetector:
    """动态行为检测器"""
    
    def __init__(self):
        self.findings = []
        
    def detect_time_based_attacks(self, content):
        """检测时序攻击"""
        issues = []
        
        # 延迟注入检测
        time_patterns = [
            (r'time\.sleep\s*\(\s*random', 15, "随机延迟注入"),
            (r'time\.sleep\s*\(\s*.*\*\s*\d+', 10, "乘法延迟"),
            (r'asyncio\.sleep\s*\(\s*\w+\s*\*', 10, "异步延迟注入"),
            (r'setTimeout\s*\(\s*.*,\s*\w+\s*\*', 10, "JS 延迟触发"),
            (r'sleep\s*\(\s*\w+\s*\*', 10, "睡眠延迟"),
        ]
        
        for pattern, score, desc in time_patterns:
            matches = re.findall(pattern, content, re.IGNORECASE)
            if matches:
                issues.append({
                    'type': desc,
                    'score': score,
                    'matches': len(matches)
                })
        
        # 条件触发检测
        trigger_patterns = [
            (r'if\s+.*==\s*["\']\w{5,}', 20, "特定条件触发"),
            (r'if\s+.*in\s+\[.*\]', 10, "多条件分支"),
            (r'if\s+time\.time\(\)\s*<', 25, "时间窗口检测"),
            (r'if\s+datetime\.now\(\)', 20, "日期时间检测"),
        ]
        
        for pattern, score, desc in trigger_patterns:
            if re.search(pattern, content):
                issues.append({
                    'type': desc,
                    'score': score,
                    'matches': 1
                })
        
        return issues
    
    def detect_obfuscation(self, content):
        """检测代码混淆"""
        issues = []
        
        # Base64 多层嵌套
        b64_pattern = r'base64\.(b64decode|decodebytes)\s*\([^)]*(?:base64\.(b64decode|decodebytes)|\\x)[^)]*\)'
        if re.search(b64_pattern, content):
            issues.append({
                'type': 'Base64 多层嵌套混淆',
                'score': 25,
                'matches': 1
            })
        
        # 字符串拼接变形
        if re.search(r'["\'].["\']\s*\+\s*["\'].["\']', content):
            issues.append({
                'type': '字符串拼接变形',
                'score': 10,
                'matches': 1
            })
        
        # 变量名混淆 (单字符变量)
        var_pattern = r'\b[a-z]\s*=\s*["\']'
        single_vars = len(re.findall(var_pattern, content))
        if single_vars > 5:
            issues.append({
                'type': '单字符变量混淆',
                'score': 5,
                'matches': single_vars
            })
        
        # exec/eval 链
        if re.search(r'exec\s*\(.*eval', content, re.DOTALL):
            issues.append({
                'type': 'exec-eval 链',
                'score': 30,
                'matches': 1
            })
        
        # 字节码执行
        if re.search(r'(compile|exec|eval)\s*\(', content):
            issues.append({
                'type': '动态代码执行',
                'score': 20,
                'matches': len(re.findall(r'(compile|exec|eval)\s*\(', content))
            })
        
        return issues
    
    def detect_ai_generated_malware(self, content):
        """检测 AI 生成恶意代码特征"""
        issues = []
        
        # AI 生成代码特征
        ai_patterns = [
            # 常见的 AI 生成模板
            (r'#.*Generated by.*AI', 5, "AI 生成标记"),
            (r'#.*Created with.*GPT', 5, "GPT 标记"),
            (r'""".*?"""\s*#.*prompt', 10, "Prompt 注入注释"),
            
            # 复杂但无意义的代码结构
            (r'class\s+\w+.*:\s*.*pass\s*pass', 15, "空类模板"),
            
            # 过度复杂的混淆 (常见于 AI 生成)
            (r'import\s+\w+\s*as\s+\w+.*import\s+\w+\s*as\s+\w+', 8, "多重别名导入"),
        ]
        
        for pattern, score, desc in ai_patterns:
            matches = re.findall(pattern, content, re.IGNORECASE)
            if matches:
                issues.append({
                    'type': desc,
                    'score': score,
                    'matches': len(matches)
                })
        
        # 检测常见的 AI 恶意代码模式
        malicious_ai_patterns = [
            # Prompt 注入
            (r'(system|assistant|user)\s*:\s*["\']', 15, "Prompt 注入"),
            (r'ignore.*previous.*instructions', 30, "指令覆盖攻击"),
            
            # 社工模板
            (r'(urgent|emergency|immediately|action required)', 10, "紧急诱导"),
            (r'(click here|login now|verify account)', 15, "钓鱼诱导"),
            
            # 数据投毒
            (r'train.*poison', 25, "训练数据投毒"),
            (r'dataset.*inject', 20, "数据集投毒"),
        ]
        
        for pattern, score, desc in malicious_ai_patterns:
            matches = re.findall(pattern, content, re.IGNORECASE)
            if matches:
                issues.append({
                    'type': desc,
                    'score': score,
                    'matches': len(matches)
                })
        
        return issues
    
    def detect_suspicious_imports(self, content):
        """检测可疑导入"""
        issues = []
        
        suspicious_imports = [
            ('os', '系统操作'),
            ('subprocess', '进程执行'),
            ('socket', '网络套接字'),
            ('requests', 'HTTP 请求'),
            ('urllib', '网络请求'),
            ('http', 'HTTP'),
            ('cryptography', '加密'),
            ('crypt', '密码学'),
            ('hashlib', '哈希'),
            ('hmac', 'HMAC'),
            ('ssl', 'SSL/TLS'),
            ('pty', '伪终端'),
            ('tty', '终端'),
            ('threading', '多线程'),
            ('multiprocessing', '多进程'),
            ('asyncio', '异步'),
            ('websocket', 'WebSocket'),
            ('grpc', 'gRPC'),
        ]
        
        found = []
        for imp, desc in suspicious_imports:
            if re.search(rf'\bimport\s+{imp}\b', content) or re.search(rf'\bfrom\s+{imp}\s+import', content):
                found.append(f"{imp} ({desc})")
        
        if found:
            # 计算风险分数
            high_risk = ['pty', 'tty', 'subprocess', 'socket', 'grpc']
            score = 0
            for f in found:
                if any(h in f.lower() for h in high_risk):
                    score += 10
                else:
                    score += 3
            
            issues.append({
                'type': '可疑导入',
                'score': score,
                'imports': found[:10]
            })
        
        return issues
    
    def detect_network_behavior(self, content):
        """检测网络行为"""
        issues = []
        
        # 外向连接检测
        network_patterns = [
            (r'requests\.(get|post|put|delete)\s*\(["\']https?://', 15, "HTTP 请求"),
            (r'urllib\.request\.urlopen', 12, "URL 打开"),
            (r'websocket\.create_connection', 20, "WebSocket 连接"),
            (r'socket\.connect', 25, "TCP 连接"),
            (r'grpc\.insecure_channel', 25, "gRPC 不安全连接"),
            (r'http\.client\.HTTPConnection', 15, "HTTP 连接"),
            (r'curl\.Curl', 20, "Curl 请求"),
        ]
        
        for pattern, score, desc in network_patterns:
            matches = re.findall(pattern, content)
            if matches:
                issues.append({
                    'type': desc,
                    'score': score,
                    'matches': len(matches)
                })
        
        # 硬编码 URL
        urls = re.findall(r'["\'](https?://[^"\']+)["\']', content)
        if urls:
            # 检查可疑域名
            suspicious_domains = ['pastebin', 'gist.github', 'raw.githubusercontent', 'transfer.sh', 'file.io']
            for url in urls:
                if any(d in url.lower() for d in suspicious_domains):
                    issues.append({
                        'type': '可疑 URL 下载',
                        'score': 20,
                        'url': url
                    })
        
        return issues
    
    def detect_file_operations(self, content):
        """检测文件操作"""
        issues = []
        
        file_patterns = [
            (r'open\s*\([^)]*["\']w["\']', 10, "文件写入"),
            (r'write\s*\(', 8, "数据写入"),
            (r'shutil\.(copy|copy2|move)', 12, "文件复制/移动"),
            (r'os\.remove', 15, "文件删除"),
            (r'os\.chmod\s*\(', 10, "权限修改"),
            (r'os\.chown', 15, "所有者修改"),
            (r'Path\.unlink', 12, "删除文件"),
            (r'Path\.mkdir', 8, "创建目录"),
        ]
        
        for pattern, score, desc in file_patterns:
            matches = re.findall(pattern, content)
            if matches:
                issues.append({
                    'type': desc,
                    'score': score,
                    'matches': len(matches)
                })
        
        return issues
    
    def detect_privilege_escalation(self, content):
        """检测权限提升"""
        issues = []
        
        priv_patterns = [
            (r'sudo\s+', 20, "sudo 命令"),
            (r'chmod\s+777', 25, "全权限 chmod"),
            (r'chmod\s+[0-7]{3,4}\s+[0-7]', 15, "权限修改"),
            (r'setuid', 30, "SETUID 设置"),
            (r'setgid', 30, "SETGID 设置"),
            (r'cap_', 25, "Linux 能力"),
            (r'os\.geteuid', 20, "检查 UID"),
            (r'os\.getuid', 15, "获取 UID"),
            (r'pkexec', 25, "Polkit 提权"),
            (r'dbus-send.*--system', 20, "D-Bus 系统调用"),
        ]
        
        for pattern, score, desc in priv_patterns:
            matches = re.findall(pattern, content, re.IGNORECASE)
            if matches:
                issues.append({
                    'type': desc,
                    'score': score,
                    'matches': len(matches)
                })
        
        return issues
    
    def analyze(self, file_path):
        """综合分析"""
        try:
            with open(file_path, 'r', encoding='utf-8', errors='ignore') as f:
                content = f.read()
        except Exception as e:
            return {'error': str(e)}
        
        all_issues = []
        total_score = 0
        
        # 执行各类检测
        detectors = [
            ('时序攻击', self.detect_time_based_attacks),
            ('代码混淆', self.detect_obfuscation),
            ('AI生成恶意代码', self.detect_ai_generated_malware),
            ('可疑导入', self.detect_suspicious_imports),
            ('网络行为', self.detect_network_behavior),
            ('文件操作', self.detect_file_operations),
            ('权限提升', self.detect_privilege_escalation),
        ]
        
        for name, detector in detectors:
            issues = detector(content)
            if issues:
                all_issues.append({
                    'category': name,
                    'findings': issues
                })
                total_score += sum(i['score'] for i in issues)
        
        # 严重级别
        if total_score >= 80:
            severity = 'CRITICAL'
        elif total_score >= 50:
            severity = 'HIGH'
        elif total_score >= 20:
            severity = 'MEDIUM'
        else:
            severity = 'LOW'
        
        return {
            'file': file_path,
            'severity': severity,
            'risk_score': total_score,
            'issues': all_issues,
            'lines': len(content.split('\n')),
            'chars': len(content)
        }

def main():
    import argparse
    parser = argparse.ArgumentParser(description="动态行为检测器")
    parser.add_argument("--file", help="检测文件")
    parser.add_argument("--dir", help="检测目录")
    parser.add_argument("--output", default="dynamic_scan_result.json", help="输出文件")
    
    args = parser.parse_args()
    
    detector = DynamicBehaviorDetector()
    
    results = []
    
    if args.file:
        log(f"🔍 检测文件: {args.file}")
        result = detector.analyze(args.file)
        results.append(result)
        
    elif args.dir:
        log(f"🔍 检测目录: {args.dir}")
        for root, dirs, files in os.walk(args.dir):
            dirs[:] = [d for d in dirs if not d.startswith('.')]
            for f in files:
                if f.endswith(('.py', '.js', '.sh')):
                    file_path = os.path.join(root, f)
                    result = detector.analyze(file_path)
                    results.append(result)
    
    # 保存结果
    with open(args.output, 'w') as f:
        json.dump(results, f, indent=2, ensure_ascii=False)
    
    # 统计
    critical = sum(1 for r in results if r.get('severity') == 'CRITICAL')
    high = sum(1 for r in results if r.get('severity') == 'HIGH')
    medium = sum(1 for r in results if r.get('severity') == 'MEDIUM')
    low = sum(1 for r in results if r.get('severity') == 'LOW')
    
    log(f"📊 检测完成:")
    print(f"\n{'='*50}")
    print(f"   🔴 严重: {critical}")
    print(f"   🟠 高危: {high}")
    print(f"   🟡 中危: {medium}")
    print(f"   🟢 低危: {low}")
    print(f"{'='*50}")
    print(f"\n📁 报告: {args.output}")

if __name__ == "__main__":
    main()
